/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniBridge */

#ifndef _Included_JniBridge
#define _Included_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniBridge
 * Method:    calcDist
 * Signature: (LCoordination;)I
 */
JNIEXPORT jint JNICALL Java_JniBridge_calcDist
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
